# app/bot/mcp_tools.py
from typing import Optional, Dict, Any, List
from app.utils.time_translator import TimeTranslator
from app.services import analytics_api, orders_api, products_api, customers_api, chatbot_users_api, suppliers_api
import logging
import re

logger = logging.getLogger(__name__)

def setup_tools(mcp):
    """Registra todas las herramientas del sistema POS en el servidor MCP."""

    # ! ANALYTICS 

    @mcp.tool()
    async def get_sales_summary(start_date: Optional[str] = None, end_date: Optional[str] = None, period: Optional[str] = None) -> Any:
        """Generates a financial and operational report (revenue, average ticket, payment methods) for a period."""
        if period:
            dates = TimeTranslator.process_request({"period": period})
            if "error" not in dates:
                start_date = dates.get("start_date")
                end_date = dates.get("end_date")
        return await analytics_api.get_sales_summary(start_date=start_date, end_date=end_date)

    @mcp.tool()
    async def get_product_ranking(limit: int = 10, criterion: str = "most", start_date: Optional[str] = None, end_date: Optional[str] = None, period: Optional[str] = None) -> Any:
        """Returns the ranking of most or least sold products. criterion must be 'most', 'least', or 'both'."""
        if period:
            dates = TimeTranslator.process_request({"period": period})
            if "error" not in dates:
                start_date = dates.get("start_date")
                end_date = dates.get("end_date")
        return await analytics_api.get_product_ranking(limit=limit, criterion=criterion, start_date=start_date, end_date=end_date)

    @mcp.tool()
    async def get_low_stock(threshold: Optional[int] = None) -> Any:
        """Identifies products with low inventory levels where current stock is less than or equal to threshold."""
        return await analytics_api.get_low_stock(threshold=threshold)

    @mcp.tool()
    async def get_dead_inventory(reference_date: Optional[str] = None) -> Any:
        """Identifies products that have had no sales since a given reference date."""
        return await analytics_api.get_dead_inventory(reference_date=reference_date)

    @mcp.tool()
    async def get_sales_velocity(identifier: str, period_days: int = 30) -> Any:
        """Calculates sales velocity and estimates days until stock depletion for a product."""
        return await analytics_api.get_sales_velocity(identifier=identifier, period_days=period_days)

    @mcp.tool()
    async def get_inventory_valuation(product_identifier: Optional[str] = None) -> Any:
        """Calculates the financial value and projected profits of the inventory."""
        return await analytics_api.get_inventory_valuation(product_identifier=product_identifier)

    @mcp.tool()
    async def get_product_contribution(product_identifier: str, start_date: Optional[str] = None, end_date: Optional[str] = None, period: Optional[str] = None) -> Any:
        """Calculates the percentage of total sales generated by a specific product."""
        if period:
            dates = TimeTranslator.process_request({"period": period})
            if "error" not in dates:
                start_date = dates.get("start_date")
                end_date = dates.get("end_date")
        return await analytics_api.get_product_contribution(product_identifier=product_identifier, start_date=start_date, end_date=end_date)

    @mcp.tool()
    async def get_customer_sales(customer_id: int, start_date: Optional[str] = None, end_date: Optional[str] = None, period: Optional[str] = None) -> Any:
        """Retrieves the purchase history, spending habits, and favorite products for a specific customer."""
        if period:
            dates = TimeTranslator.process_request({"period": period})
            if "error" not in dates:
                start_date = dates.get("start_date")
                end_date = dates.get("end_date")
        return await analytics_api.get_customer_sales(customer_id=customer_id, start_date=start_date, end_date=end_date)

    # ! ORDERS MODULE 

    @mcp.tool()
    async def get_order_detail(order_id: int) -> Any:
        """Retrieves the full details of a specific order or ticket."""
        return await orders_api.get_order_detail(order_id=order_id)

    @mcp.tool()
    async def search_recent_orders(ticket_folio: Optional[str] = None, status: Optional[str] = None, limit: int = 10) -> Any:
        """Searches recent orders by folio, status (PENDING, PAID, CANCELLED), or gets a general list."""
        return await orders_api.search_recent_orders(ticket_folio=ticket_folio, status=status, limit=limit)

    # ! PRODUCTS MODULE

    @mcp.tool()
    async def get_total_product_count() -> Dict[str, int]:
        """Returns the total number of products currently in the catalog."""
        data = await products_api.get_all_products()
        return {"total_products": len(data)}

    @mcp.tool()
    async def search_products_in_inventory(
        id: Optional[int] = None,
        name: Optional[str] = None,
        sku: Optional[str] = None,
        supplier_id: Optional[int] = None,
        low_stock: Optional[bool] = None,
        price: Optional[float] = None,
        final_price: Optional[float] = None,
        tax_rate: Optional[float] = None,
        tax_rate_display: Optional[str] = None,
        updated_after: Optional[str] = None # Format: ISO
    ) -> List[Dict[str, Any]]:
        """
        Search products using any specific parameter from the database.
        Returns the full product object for the matches found.
        """
        data = await products_api.get_all_products()
        results = data

        if id: results = [p for p in results if p["id"] == id]
        if name: results = [p for p in results if name.lower() in p["name"].lower()]
        if sku: results = [p for p in results if sku.lower() in p["sku"].lower()]
        if supplier_id: results = [p for p in results if p["supplier"] == supplier_id]
        if low_stock is not None: results = [p for p in results if p["low_stock"] == low_stock]
        if price: results = [p for p in results if float(p["price"]) == price]
        if final_price: results = [p for p in results if float(p["final_price"]) == final_price]
        if tax_rate: results = [p for p in results if float(p["tax_rate"]) == tax_rate]
        if tax_rate_display: results = [p for p in results if tax_rate_display.lower() in p["tax_rate_display"].lower()]
        if updated_after: results = [p for p in results if p["updated_at"] >= updated_after]

        return results[:20]

    @mcp.tool()
    async def get_all_promotions() -> Any:
        """Retrieves all currently active promotions, discounts, and sales."""
        return await products_api.get_all_promotions()

    @mcp.tool()
    async def get_promotions_by_product(product_id: int) -> Any:
        """Checks if a specific product has any active discounts or promotions."""
        return await products_api.get_promotions_by_product(product_id=product_id)

    # !  CUSTOMERS MODULE

    def clean_money(value: str) -> float:
        if not value: return 0.0
        return float(re.sub(r'[^\d.]', '', str(value)))

    @mcp.tool()
    async def get_total_customer_count() -> Dict[str, int]:
        """Returns the total number of registered customers."""
        data = await customers_api.get_all_customers()
        return {"total_customers": len(data)}

    @mcp.tool()
    async def search_customers(
        id: Optional[int] = None,
        name: Optional[str] = None,
        is_frequent: Optional[bool] = None,
        has_debt: Optional[bool] = None,
        min_points: Optional[int] = None,
        birth_month: Optional[int] = None
    ) -> List[Dict[str, Any]]:
        """
        Advanced customer search with unified name lookup and financial filters.
        """
        data = await customers_api.get_all_customers()
        results = data

        if id: 
            results = [c for c in results if c["id"] == id]
    
        if name:
            query = name.lower()
        else:
            query=""

        results = [
            c for c in results 
            if query in f"{c['first_name']} {c['last_name']}".lower()
            ]

        if is_frequent is not None: 
            results = [c for c in results if (c["frequent_customer"] == "Yes") == is_frequent]
    
        if has_debt is not None:
            results = [c for c in results if (clean_money(c["credit_used"]) > 0) == has_debt]
    
        if min_points:
            results = [c for c in results if int(c["current_points"]) >= min_points]
        
        if birth_month:
            results = [c for c in results if int(c["birth_date"].split("-")[1]) == birth_month]

        return results[:20]

    @mcp.tool()
    async def get_customer_points_history(customer_id: int) -> Any:
        """Retrieves the loyalty points history and redemption records for a customer."""
        return await customers_api.get_customer_points_history(customer_id=customer_id)

    @mcp.tool()
    async def get_customer_credit_history(customer_id: int) -> Any:
        """Retrieves the credit history, current debt, available credit, and payment records for a customer."""
        return await customers_api.get_customer_credit_history(customer_id=customer_id)

    @mcp.tool()
    async def get_customer_detail(customer_id: int) -> Any:
        """Retrieves the full personal profile, contact email, and demographic info (e.g., birthday) of a customer."""
        return await customers_api.get_customer_detail(customer_id=customer_id)

    # ! CHATBOT USERS MODULE 

    @mcp.tool()
    async def get_all_chatbot_users() -> Any:
        """Retrieves the whitelist of users authorized to interact with the bot."""
        return await chatbot_users_api.get_all_chatbot_users()

    @mcp.tool()
    async def get_chatbot_user(mobile_number: str) -> Any:
        """Verifies access and last connection details for a specific bot user by their mobile number."""
        return await chatbot_users_api.get_chatbot_user(mobile_number=mobile_number)
    
    # ! SUPPLIERS MODULE 

    @mcp.tool()
    async def get_total_supplier_count() -> Dict[str, int]:
        """Returns the total number of registered suppliers."""
        data = await suppliers_api.get_all_suppliers()
        return {"total_suppliers": len(data)}

    @mcp.tool()
    async def search_suppliers(
        id: Optional[int] = None,
        name: Optional[str] = None,
        contact_person: Optional[str] = None,
        rfc: Optional[str] = None,
        tax_address: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """
        Advanced supplier lookup. 
        Use this to find specific contact details, RFC, or physical addresses.
        """ 
        data = await suppliers_api.get_all_suppliers()
        results = data

        if id: results = [s for s in results if s["id"] == id]
        if name: results = [s for s in results if name.lower() in s["name"].lower()]
        if contact_person: results = [s for s in results if contact_person.lower() in s["contact_person"].lower()]
        if rfc: results = [s for s in results if rfc.upper() in s["rfc"].upper()]
        if tax_address: results = [s for s in results if tax_address.lower() in s["tax_address"].lower()]

        return results[:15] 

    @mcp.tool()
    async def get_supplier_detail(supplier_id: int) -> Any:
        """
        Retrieves full tax identification (RFC/Tax ID) and contact details (email, phone, address) 
        of a specific supplier by its ID.
        """
        return await suppliers_api.get_supplier_detail(supplier_id=supplier_id)